version: 1.0.3.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
build_script:
- ps: ./build.ps1
artifacts:
- path: artifacts/Sddl.Parser.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: c2wv6IzJQxZaIa4PuQ8Z9qh6BQD/Loi+YjXGtSQ4s3d6ZN8myHKCTsliIItuCAZJ
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: EvmK1D7sNtMe+DI38I00V9RIZThuFPhqEPlL5MNNRDUyLjcoxU0EyEcSxo/ynbJg
  artifact: /Sddl.Parser.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
